/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    documents: Document;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hi') | ('en' | 'hi')[];
  globals: {
    home: Home;
    objectives: Objective;
    'governing-body': GoverningBody;
    'whos-who': WhosWho;
    tenders: Tender;
    services: Service;
    'documents-page': DocumentsPage;
    'photo-gallery': PhotoGallery;
    'apuni-sarkar': ApuniSarkar;
    darc: Darc;
    'data-center': DataCenter;
    'cm-helpline': CmHelpline;
    'e-office': EOffice;
    'uk-swan': UkSwan;
    'e-gate-pass': EGatePass;
    aadhar: Aadhar;
    'itda-calc': ItdaCalc;
    'gati-shakti': GatiShakti;
    'main-services': MainService;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    objectives: ObjectivesSelect<false> | ObjectivesSelect<true>;
    'governing-body': GoverningBodySelect<false> | GoverningBodySelect<true>;
    'whos-who': WhosWhoSelect<false> | WhosWhoSelect<true>;
    tenders: TendersSelect<false> | TendersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'documents-page': DocumentsPageSelect<false> | DocumentsPageSelect<true>;
    'photo-gallery': PhotoGallerySelect<false> | PhotoGallerySelect<true>;
    'apuni-sarkar': ApuniSarkarSelect<false> | ApuniSarkarSelect<true>;
    darc: DarcSelect<false> | DarcSelect<true>;
    'data-center': DataCenterSelect<false> | DataCenterSelect<true>;
    'cm-helpline': CmHelplineSelect<false> | CmHelplineSelect<true>;
    'e-office': EOfficeSelect<false> | EOfficeSelect<true>;
    'uk-swan': UkSwanSelect<false> | UkSwanSelect<true>;
    'e-gate-pass': EGatePassSelect<false> | EGatePassSelect<true>;
    aadhar: AadharSelect<false> | AadharSelect<true>;
    'itda-calc': ItdaCalcSelect<false> | ItdaCalcSelect<true>;
    'gati-shakti': GatiShaktiSelect<false> | GatiShaktiSelect<true>;
    'main-services': MainServicesSelect<false> | MainServicesSelect<true>;
  };
  locale: 'en' | 'hi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Homepage
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  carousel?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  notifications: {
    title: string;
    link: string;
    id?: string | null;
  }[];
  members: {
    name: string;
    designation: string;
    image: string | Media;
    id?: string | null;
  }[];
  about: {
    images: {
      image?: (string | null) | Media;
      id?: string | null;
    }[];
    heading: string;
    title: string;
    description: string;
    link: string;
  };
  projects: {
    projects: {
      image: string | Media;
      title: string;
      subTitle: string;
      link: string;
      id?: string | null;
    }[];
    title: string;
  };
  partners: {
    image: string | Media;
    link: string;
    id?: string | null;
  }[];
  photoGallery: {
    centerImage: string | Media;
    leftCarousel: {
      image: string | Media;
      id?: string | null;
    }[];
    rightCarousel: {
      image: string | Media;
      id?: string | null;
    }[];
  };
  homepageGallery: {
    image: string | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Objectives
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objectives".
 */
export interface Objective {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  itdaFunction: {
    subHeading: string;
    points: {
      point: string;
      id?: string | null;
    }[];
  };
  members: {
    name: string;
    designation: string;
    image: string | Media;
    id?: string | null;
  }[];
  about: {
    heading: string;
    title: string;
    description: string;
  };
  itdaObjectives: {
    subTitle: string;
    projects: {
      image: string | Media;
      title: string;
      subTitle: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Governing Body
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governing-body".
 */
export interface GoverningBody {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heading: string;
  description: string;
  members: {
    sno: number;
    name: string;
    position: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * whos-who
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whos-who".
 */
export interface WhosWho {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  departments: {
    wingName: string;
    officials: {
      name: string;
      /**
       * i18n hook text trigger key (e.g., director, jointDirector)
       */
      designationKey: string;
      email: string;
      image?: (string | null) | Media;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Tenders Settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders".
 */
export interface Tender {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  documents: {
    documentName: string;
    fileDoc: string | Document;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Acts-And-Rules Data
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  category: {
    categoryName: string;
    services: {
      name: string;
      description: string;
      link: string;
      color: 'cream' | 'leafGreen' | 'blue' | 'mintGreen';
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page".
 */
export interface DocumentsPage {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  documents: {
    documentName: string;
    fileDoc: string | Document;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Photo Gallery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-gallery".
 */
export interface PhotoGallery {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  photoGallery: {
    image: string | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Apuni Sarkar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apuni-sarkar".
 */
export interface ApuniSarkar {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  link: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Darc
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "darc".
 */
export interface Darc {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  missionAndVision: string;
  missinoAndVisionPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  objective: string;
  objectivePoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Data Center
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-center".
 */
export interface DataCenter {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  vision: string;
  visionInfo: string;
  mission: string;
  missionDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  functionalities: string;
  functionalitiesDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * CM Helpline
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cm-helpline".
 */
export interface CmHelpline {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  visit: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * E-Office
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "e-office".
 */
export interface EOffice {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  objectives: string;
  objectivesPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  uttrakhandStatus: string;
  uttrakhandStatusPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * UK SWAN
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uk-swan".
 */
export interface UkSwan {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  highlights: string;
  highlightsPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * E-Gate Pass
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "e-gate-pass".
 */
export interface EGatePass {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  visitLink: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  link: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Aadhar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aadhar".
 */
export interface Aadhar {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  stats: string;
  statPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * ITDA CALC
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itda-calc".
 */
export interface ItdaCalc {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  visitLink: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Gati Shakti
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gati-shakti".
 */
export interface GatiShakti {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  heroImage: string | Media;
  heading: string;
  about: string;
  accessiblePoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  features: string;
  featuresPoints: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Services
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-services".
 */
export interface MainService {
  id: string;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  category: {
    categoryName: string;
    services: {
      name: string;
      description: string;
      link: string;
      color: 'cream' | 'leafGreen' | 'blue' | 'mintGreen';
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  carousel?:
    | T
    | {
        image?: T;
        id?: T;
      };
  notifications?:
    | T
    | {
        title?: T;
        link?: T;
        id?: T;
      };
  members?:
    | T
    | {
        name?: T;
        designation?: T;
        image?: T;
        id?: T;
      };
  about?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        heading?: T;
        title?: T;
        description?: T;
        link?: T;
      };
  projects?:
    | T
    | {
        projects?:
          | T
          | {
              image?: T;
              title?: T;
              subTitle?: T;
              link?: T;
              id?: T;
            };
        title?: T;
      };
  partners?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  photoGallery?:
    | T
    | {
        centerImage?: T;
        leftCarousel?:
          | T
          | {
              image?: T;
              id?: T;
            };
        rightCarousel?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  homepageGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objectives_select".
 */
export interface ObjectivesSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  itdaFunction?:
    | T
    | {
        subHeading?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
      };
  members?:
    | T
    | {
        name?: T;
        designation?: T;
        image?: T;
        id?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        title?: T;
        description?: T;
      };
  itdaObjectives?:
    | T
    | {
        subTitle?: T;
        projects?:
          | T
          | {
              image?: T;
              title?: T;
              subTitle?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "governing-body_select".
 */
export interface GoverningBodySelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heading?: T;
  description?: T;
  members?:
    | T
    | {
        sno?: T;
        name?: T;
        position?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whos-who_select".
 */
export interface WhosWhoSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  departments?:
    | T
    | {
        wingName?: T;
        officials?:
          | T
          | {
              name?: T;
              designationKey?: T;
              email?: T;
              image?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders_select".
 */
export interface TendersSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  documents?:
    | T
    | {
        documentName?: T;
        fileDoc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  category?:
    | T
    | {
        categoryName?: T;
        services?:
          | T
          | {
              name?: T;
              description?: T;
              link?: T;
              color?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents-page_select".
 */
export interface DocumentsPageSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  documents?:
    | T
    | {
        documentName?: T;
        fileDoc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-gallery_select".
 */
export interface PhotoGallerySelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  photoGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apuni-sarkar_select".
 */
export interface ApuniSarkarSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  description?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "darc_select".
 */
export interface DarcSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  missionAndVision?: T;
  missinoAndVisionPoints?: T;
  objective?: T;
  objectivePoints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-center_select".
 */
export interface DataCenterSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  vision?: T;
  visionInfo?: T;
  mission?: T;
  missionDescription?: T;
  functionalities?: T;
  functionalitiesDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cm-helpline_select".
 */
export interface CmHelplineSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  visit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "e-office_select".
 */
export interface EOfficeSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  objectives?: T;
  objectivesPoints?: T;
  uttrakhandStatus?: T;
  uttrakhandStatusPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uk-swan_select".
 */
export interface UkSwanSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  highlights?: T;
  highlightsPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "e-gate-pass_select".
 */
export interface EGatePassSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  visitLink?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aadhar_select".
 */
export interface AadharSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  stats?: T;
  statPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itda-calc_select".
 */
export interface ItdaCalcSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  visitLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gati-shakti_select".
 */
export interface GatiShaktiSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  heroImage?: T;
  heading?: T;
  about?: T;
  accessiblePoints?: T;
  features?: T;
  featuresPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-services_select".
 */
export interface MainServicesSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  category?:
    | T
    | {
        categoryName?: T;
        services?:
          | T
          | {
              name?: T;
              description?: T;
              link?: T;
              color?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}